---
title: "Metadata"
author: "Lisa"
output:
rmarkdown::html_document:
   theme: united
   highlight: tango
   code_folding: hide
   toc: true
   toc_float: true
   df_print: paged
   smooth_scroll: true
   number_sections: false
   self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
setwd("/Volumes/Samsung_T5/MiG_data/MDD_microglia_analysis/MDD_microglia_analysis/AD_analyses")
library(ProjectTemplate)
load.project()
```

```{r packages, echo=FALSE, message=FALSE, results='hide'}
library(UpSetR)
library(readxl)
library(knitr)
library(kableExtra)
library(ggplot2)
library(RColorBrewer)
library(tidyverse)
```

# Preparing metadata 
## Change to correct data format

```{r changing format}
metadata <- X202104021_metadata_tidy.Blad1
metadata$Diagnosis <- as.factor(metadata$Diagnosis)
metadata$Main_diagnosis <- as.factor(metadata$Main_diagnosis)
metadata$Region <- as.factor(metadata$Tissue)
#repeat this for AD columns?
```

## Number of unique donors

```{r unique donors, echo=TRUE}
#set rownames to Donor_tissue
# row.names(metadata) <- metadata$Donor_tissue
length(unique(metadata$Donor_id)) 
```

## Number of Antidepressant users 

```{r antidressant users, echo=TRUE}
#create new dataframe with only AD users
metadata_AD <- metadata[metadata[,"Antidepressant_90days"]== "YES",] 
length(unique(metadata_AD$Donor_id))

```
## Number of Patients using both Antidepressants and Antipsychotics 
```{r, echo=TRUE}
metadata_ADAP <- metadata_AD[metadata_AD[, "Antipsychotica_90days"]== "YES",]
length(unique(metadata_ADAP$Donor_id))
donor_AD_AP <- unique(metadata_ADAP$Donor_id)
```

## Number of patients per antidepressant type 
```{r, echo=TRUE}
donor_AD = unique(metadata_AD[,c("Donor_id", "Antidepressant_1", "Antidepressant_2")])

#check which donors only use 1 AD
donor_AD[donor_AD[,"Antidepressant_2"]=='NO',]

as.data.frame(t(as.matrix(unclass(table(c(donor_AD$Antidepressant_1,donor_AD$Antidepressant_2), useNA = "ifany")  )))) %>%
kable(row.names = F) %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

```

## Number of samples per antidepressant type 
```{r}
as.data.frame(t(as.matrix(unclass(table(metadata$Antidepressant_90days, useNA = "ifany")  )))) %>%
kable(row.names = F) %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

```





## Upset plot 

