---
title: "PCA_after_filtering"
author: "LB"
date: "5/17/2021"
output: html_document
rmarkdown::html_document:
   theme: united
   highlight: tango
   code_folding: hide
   toc: true
   toc_float: true
   df_print: paged
   smooth_scroll: true
   number_sections: false
   self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load.packages, echo=FALSE, message=FALSE, results='hide'}
library(devtools)
library(factoextra)
library(ggfortify)
library(ggplot2)
library(dplyr)
library(broom)
library(variancePartition)
library(pheatmap)
library(edgeR)
library(limma)
library(DESeq2)
library(Hmisc)
library(matrixStats)


knitr::opts_chunk$set( 
  warning=FALSE,
  message=FALSE,
  results = 'asis',
  error = FALSE,
  tidy = FALSE,
  fig.show = "hold")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/Volumes/Samsung_T5/MiG_data/MDD_microglia_analysis/MDD_microglia_analysis/AD_analyses")
library(ProjectTemplate)
load.project()
```

```{r directory}
data_dir <- "/Volumes/Samsung_T5/MiG_data/MDD_microglia_analysis/MDD_microglia_analysis/AD_analyses/data"
project_dir <- "/Volumes/Samsung_T5/MiG_data/MDD_microglia_analysis/MDD_microglia_analysis/AD_analyses"
```

```{r load_data, echo=TRUE, results = 'hide'}
load("/Volumes/Samsung_T5/MiG_data/MDD_microglia_analysis/MDD_microglia_analysis/AD_analyses/data/gene_matrix.RData")
metadata = "/Volumes/Samsung_T5/MiG_data/MDD_microglia_analysis/MDD_microglia_analysis/AD_analyses/data/metadata_gen_stats_alt.xslx"
metadata = read_excel(metadata, col_names = TRUE) 
metadata = as.data.frame(metadata)
row.names(metadata) <- metadata$Donor_tissue

#this excludes the samples selected after quality control 
exclude_qc <- read.table("/Volumes/Samsung_T5/MiG_data/MDD_microglia_analysis/MDD_microglia_analysis/AD_analyses/data/samples2remove_28s.txt")
exclude_qc <- exclude_qc[-1,]

#this excludes the samples without medication information
exclude_na <- read.table("/Volumes/Samsung_T5/MiG_data/MDD_microglia_analysis/MDD_microglia_analysis/AD_analyses/data/samples2remove_drugNA.txt")
exclude_na<- exclude_na$x

exclude_total <- unique(c(exclude_na, exclude_qc))
#save(exclude_total, file="/Volumes/Samsung_T5/MiG_data/MDD_microglia_analysis/MDD_microglia_analysis/AD_analyses/data/exclude_total.rda") 
#now use load("/Volumes/Samsung_T5/MiG_data/MDD_microglia_analysis/MDD_microglia_analysis/AD_analyses/data/exclude_total.rda")

  
colnames(genes_counts)[1] <- "13-072-CC" 
genes_counts_filt = genes_counts[, !colnames(genes_counts) %in% exclude_qc]
metadata_filt = metadata[ !(rownames(metadata) %in% exclude_qc), ]
length(metadata_filt)

genes_counts_filt = genes_counts[, !colnames(genes_counts) %in% exclude_na]
metadata_filt = metadata[ !(rownames(metadata) %in% exclude_na), ]
length(metadata_filt)

#remove low count genes
cpm <- cpm(genes_counts_filt) 
# CPM >= 1 in at least 50% of the samples
keep.exp <- rowSums(cpm > 1) >= (0.5 * ncol(genes_counts_filt) )
genes_counts_filt1 <- genes_counts_filt[ keep.exp, ] #15433 genes 
#performing voom normalisation on data
counts_voom <- limma::voom(genes_counts_filt1)
genes_counts_voom <- counts_voom$E
#order metadata and genes counts
#rownames(metadata)
#colnames(genes_counts_voom)

genes_counts_ordered <- genes_counts_voom[,rownames(metadata_filt)]
#head(genes_counts_ordered)
all(rownames(metadata_filt) == colnames (genes_counts_ordered)) #TRUE
```
# PCA 
#After filtering: 264 samples in total 

```{r PCA, echo=TRUE, fig.width=12, fig.height=8, dpi=300}
pca = prcomp(t(genes_counts_ordered), scale. = TRUE, center = TRUE)
autoplot(pca, data= metadata_filt, colour = 'Drugs', shape = FALSE, label.size = 2)
```

# Heatmap with 20 PCS 

```{r heatmap_all, echo=TRUE, fig.width=12, fig.height=8, dpi=300}
#set metadata to no capitals
names(metadata_filt) = tolower(names(metadata_filt))
indx <- sapply(metadata, is.character)
metadata[indx] <- lapply(metadata[indx], function(x) as.factor(x))

#include covariates
covariates = c( "donor_id",
                "diagnosis",
                "main_diagnosis",
                "tissue",
                "sex",
                "age",
                "pmd_minutes",
                "ph",
                "cause_of_death_categories",
                "smoking",
                "alcohol_dependence_daily_use",
                "autoimmune_diseases",
                "infection_2weeks",
                "drugs",
                "antidepressant_90days",
                "antidepressant_1",
                "antidepressant_2",
                "dose_mg", 
                "dose2_mg", 
                "antipsychotica_90days",
                "antipsychotica_typical",
                "antipsychotica_atypical",
                "dose_typical",
                "dose_atypical",
                "narcotics_90days",
                "benzo_90days",
                "other",
                "immuno",
                "ad last year?",
                "ad ever?",
                "picard_pct_mrna_bases",
                "picard_pct_ribosomal_bases",
                "picard_pct_pf_reads_aligned",
                "picard_summed_median",
                "picard_summed_mean")

#create format matrix 
matrix_rsquared = matrix(NA, nrow = length(covariates), ncol = 20) #Number of factors
matrix_pvalue = matrix(NA, nrow = length(covariates), ncol = 20)
#lineair model function 
for (x in 1:length(covariates)){
  for (y in 1:20){
    matrix_rsquared[x,y] <- summary( lm(pca$x[,y] ~ metadata_filt[,covariates[x]]) )$adj.r.squared
    matrix_pvalue[x,y] <- tidy( lm(pca$x[,y] ~ metadata_filt[,covariates[x]]) )$p.value[2] #To insert pvalues in the heatmap
  }
}

#fill matrix with values 
matrix_rsquared <- as.data.frame(matrix_rsquared)
matrix_pvalue <- as.data.frame(matrix_pvalue)
rownames(matrix_rsquared) <- covariates
rownames(matrix_pvalue) <- covariates 
#create heatmap with rsquared values 
pheatmap(matrix_rsquared, main = "Correlation (Rsquared) between variables and first 20 PCs", legend = TRUE)
```
### Boxplot PC10 
#Variance somewhat driven by antidepressant type

```{r boxplot_PC10, echo=TRUE}
PC1 <- pca$x[,10]
AD1 <- metadata_filt$antidepressant_1
df = data.frame(AD1, PC1)
ggplot(data = df, mapping = aes(x = AD1, y = PC1)) +
  geom_boxplot()
```

Variance driven by diagnosis
```{r boxplot_PC10, echo=TRUE}
PC10 <- pca$x[,10]
Diagnosis <- metadata_filt$diagnosis
df = data.frame(Diagnosis, PC10)
ggplot(data = df, mapping = aes(x = Diagnosis, y = PC10)) +
  geom_boxplot()
```
Variance driven by Main diagnosis 
```{r boxplot_PC10, echo=TRUE}
PC10 <- pca$x[,10]
m_diagnosis <- metadata_filt$main_diagnosis
df = data.frame(m_diagnosis, PC10)
ggplot(data = df, mapping = aes(x = m_diagnosis, y = PC10)) +
  geom_boxplot()
```

# PCA most variable genes (excluding uncultured)
### 1000 most variable genes 

```{r PCA_variable_1000, echo=TRUE}
rv <- rowVars(as.matrix(genes_counts_filt1))
  select <- order(rv, decreasing = TRUE)[1:1000]
  pca <- prcomp(t(genes_counts_filt1[select, ]), scale. = TRUE, center = TRUE)
  autoplot(pca, data= metadata_filt, colour = "drugs", shape = FALSE, label.size = 2)
  autoplot(pca, colour = "drugs", data = metadata_filt)
```

### 500 most variable genes 

```{r PCA_variable_500, echo=TRUE}
rv <- rowVars(as.matrix(genes_counts_filt1))
  select <- order(rv, decreasing = TRUE)[1:500]
  pca <- prcomp(t(genes_counts_filt1[select, ]), scale. = TRUE, center = TRUE)
  autoplot(pca, data= metadata_filt, colour = 'drugs', shape = FALSE, label.size = 2)
  autoplot(pca, colour = "drugs", data = metadata_filt)
```
