---
title: "StepAIC"
author: "LB"
date: "5/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load.packages, echo=FALSE, message=FALSE, results='hide'}
library(variancePartition)
library(edgeR)

knitr::opts_chunk$set( 
  warning=FALSE,
  message=FALSE,
  results = 'asis',
  error = FALSE,
  tidy = FALSE,
  fig.show = "hold")
```

```{r setup, echo=FALSE, message=FALSE, results='hide'}
setwd("/Volumes/Samsung_T5/MiG_data/MDD_microglia_analysis/MDD_microglia_analysis/AD_analyses")
library(ProjectTemplate)
load.project()
```

```{r load_data, echo=TRUE, results = 'hide'}
load("/Volumes/Samsung_T5/MiG_data/MDD_microglia_analysis/MDD_microglia_analysis/AD_analyses/data/gene_matrix.RData")
metadata = "/Volumes/Samsung_T5/MiG_data/MDD_microglia_analysis/MDD_microglia_analysis/AD_analyses/data/metadata_gen_stats_alt.xslx"
metadata = read_excel(metadata, col_names = TRUE) 
metadata = as.data.frame(metadata)
row.names(metadata) <- metadata$Donor_tissue

load("/Volumes/Samsung_T5/MiG_data/MDD_microglia_analysis/MDD_microglia_analysis/AD_analyses/data/exclude_total.rda")

``` 

```{r}
colnames(genes_counts)[1] <- "13-072-CC"
genes_counts_filt = genes_counts[, !colnames(genes_counts) %in% exclude_total] #238 variables 
metadata_filt = metadata[ !(rownames(metadata) %in% exclude_total), ] #238 variables 
cpm <- cpm(genes_counts_filt)
# CPM >= 1 in at least 50% of the samples
keep.exp <- rowSums(cpm > 1) >= (0.5 * ncol(genes_counts_filt) )
genes_counts5 <- genes_counts_filt[keep.exp, ] #15487 genes 
#performing voom normalisation on data
counts_voom <- limma::voom(genes_counts5)
genes_counts_voom <- counts_voom$E
#order metadata and genes counts

genes_counts_ordered <- genes_counts_voom[,rownames(metadata_filt)]
head(genes_counts_ordered)
all(rownames(metadata_filt) == colnames (genes_counts_ordered)) #TRUE

```



Do this step with gene counts or tpm ? 
```{r stepAIC}
#transpose the tpm data frame so the donor_tissue is in both df's a column. 
genes_tpm_filt_t<-as.data.frame(t(genes_tpm_filt))
#add donor_tissue as a column. now these are rowsnames. 
genes_tpm_filt_t2 <- cbind(names = rownames(genes_tpm_filt_t), genes_tpm_filt_t)
colnames(genes_tpm_filt_t2)[1]<- "donor_tissue"
#merge these dataframes 
genes_tpm_filt_combined <- merge(genes_tpm_filt_t2, metadata_filt, by="donor_tissue")

#now change column "donor_tissue" into rownames (?) 
genes_tpm_filt_combined <- column_to_rownames(genes_tpm_filt_combined, var = "donor_tissue")

```

```{r}

model1 <- lm(?? ~covariate + covariate +..)

    
stepAIC(model1, direction = "backward", data = ..., test = "F")


```